# Generated by Django 5.0.6 on 2024-05-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_cart_orders_remove_client_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='cart',
        ),
    ]
