# Generated by Django 5.0.6 on 2024-05-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_client_client_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.client'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.cart'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.clientinfo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.seller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.sellerinfo'),
        ),
    ]
