# Generated by Django 5.0.6 on 2024-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_productreview_sellerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_id',
            field=models.UUIDField(default='62a0fbc39f0d4c53b5a5d9ab82615665'),
            preserve_default=False,
        ),
    ]
