# Generated by Django 5.0.6 on 2024-05-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_productreview_sellerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='isEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.client')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.seller')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.client')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.seller')),
            ],
        ),
    ]
