# Generated by Django 5.0.6 on 2024-06-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_purchase_product_id'),
        ('apps', '0011_client_isenabled_seller_isenabled_activationtoken_and_more'),
    ]

    operations = [
    ]
